name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ x86_64 ]
        debug: [ DEBUG, NON-DEBUG ]
    concurrency:
      group: release-${{ matrix.debug }}
    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{github.ref_name}} ${{github.sha}}

      - name: Setup | Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup | Install Inno Setup & UPX & 7-Zip
        run: choco install innosetup upx 7zip -y

      - name: Build | Build PowerToysRunEnhance
        env:
          NEW_VERSION: "0.1.0"
          GITHUB_ACTIONS: "true"
          ARCH: ${{ matrix.arch }}
          DEBUG: ${{ matrix.debug }}
          UPX: "false"
          PYTHON: "cpython-3.12.9-windows-${{ matrix.arch }}-none"
        run: |
          .\scripts\build.ps1

      - name: Prepare artifacts for upload
        run: |
          mkdir -p artifacts-${{ matrix.arch }}-${{ matrix.debug == 'DEBUG' && 'Debug' || '' }}
          cp -r src/Output/* artifacts-${{ matrix.arch }}-${{ matrix.debug == 'DEBUG' && 'Debug' || '' }}/

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: artifacts-${{ matrix.arch }}-${{ matrix.debug == 'DEBUG' && 'Debug' || '' }}
          key: build-artifacts-${{ matrix.arch }}-${{ matrix.debug == 'DEBUG' && 'Debug-' || '' }}${{github.sha}}

  upload:
    name: Upload
    needs: build
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ x86_64 ]
        debug: [ DEBUG, NON-DEBUG ]
    steps:
      - name: Restore cached build artifacts
        uses: actions/cache@v4
        with:
          path: artifacts-${{ matrix.arch }}-${{ matrix.debug == 'DEBUG' && 'Debug' || '' }}
          key: build-artifacts-${{ matrix.arch }}-${{ matrix.debug == 'DEBUG' && 'Debug-' || '' }}${{ github.sha }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PowerToysRunEnhance-CI-${{ matrix.arch }}-${{ matrix.debug == 'DEBUG' && 'Debug-' || '' }}${{ github.sha }}
          path: artifacts-${{ matrix.arch }}-${{ matrix.debug == 'DEBUG' && 'Debug' || '' }}/*
          if-no-files-found: error