name: Release

on:
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    concurrency: release
    outputs:
      version: ${{ steps.release.outputs.version }}
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Action | Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          changelog: true
          github_token: ${{ secrets.GH_PAT }}
          git_committer_name: ${{vars.GH_USERNAME}}
          git_committer_email: ${{vars.GH_EMAIL}}

  build:
    name: Build
    needs: prepare
    strategy:
      matrix:
        arch: [ x86_64 ]
    runs-on: windows-latest

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup | Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup | Install Inno Setup & UPX & 7-Zip
        run: choco install innosetup upx 7zip -y

      - name: Build | Build PowerToysRunEnhance
        id: build
        env:
          NEW_VERSION: ${{ needs.prepare.outputs.version }}
          GITHUB_ACTIONS: "true"
          ARCH: ${{ matrix.arch }}
          UPX: "false"
          PYTHON: "cpython-3.12.9-windows-${{matrix.arch}}-none"
        run: .\scripts\build.ps1

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: src/Output
          key: build-artifacts-${{github.sha}}
          enableCrossOsArchive: true

  publish:
    name: Publish
    needs: [prepare, build]
    runs-on: ubuntu-latest
    if: needs.prepare.outputs.released == 'true'
    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached build artifacts
        uses: actions/cache@v4
        with:
          path: src/Output
          key: build-artifacts-${{github.sha}}

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.21.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          tag: ${{ needs.prepare.outputs.tag }}

